### ISSUE TITLE
OpenGL enum error on Mac OSX

### ISSUE THREAD

**Issue by apatzer** [amarburg/lsd_slam#1]
Hi @amarburg, great refactor of LSD-Slam. I've got your code up and running on a Mac (pulled out the ZED camera and Snappy, but otherwise identical), and can only get the Pangolin UI to run with freeglut (seg fault on the built-in Mac GLUT).

However, it seems that I'm getting a GL enum error.

![image](https://cloud.githubusercontent.com/assets/2538644/15100670/e36f0a6a-15cc-11e6-903b-baa5ed6a1aff.png)

Any recommended solution?

I've tried defining __gl3_h_ to ensure that a newer version of OpenGL isn't being brought into either Pangolin or LSD-Slam but to no avail.

**Comment by apatzer** [comment]
Ignoring the error and letting the system run, I will eventually get to:

```
2016-05-09 12:05:15.073 LSD[56322:21039787] *** Assertion failure in +[NSScreen _invalidateIfNeededForReason:], /Library/Caches/com.apple.xbs/Sources/AppKit/AppKit-1404.46/AppKit.subproj/NSScreen.m:1067
2016-05-09 12:05:15.075 LSD[56322:21039787] An uncaught exception was raised
2016-05-09 12:05:15.075 LSD[56322:21039787] NSScreen reconfig must only happen on the main thread.
```

Essentially on OSX it seems like all UI rendering must be on the main thread. Have you successfully run the GUI on a Mac?

**Comment by amarburg** [comment]
Thanks.   Still a work in progress, obviously.   I hope you were able to pull out the Snappy and Zed stuff by disabling it in Cmake .... otherwise my integration needs more work.

I also had to force Pangolin to compile with Freeglut (see "Common Problems" in the readme) and I had the same enum problem.   So far, my experience has been that it's annoying but non-fatal -- I haven't seen the error from your second post.

**Comment by amarburg** [comment]
Things have obviously moved on in the last 9 months.   

In the current state of play, this 1280 error is explicitly squelched via a patch (cmake/Pangolin_squelch_error_1280.patch) which is applied by make/BuildPangolin.cmake.
